# Generated by Django 4.1.1 on 2022-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rawmaterialusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialusage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
