# Generated by Django 4.1.1 on 2022-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_timestampedmaterialupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestampedmaterialupdate',
            name='date_created',
        ),
        migrations.AddField(
            model_name='timestampedmaterialupdate',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='timestampedmaterialupdate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
