# Generated by Django 4.1.1 on 2022-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_branch_site_rawmaterial_confirm_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsale',
            name='sale_by',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
