# Generated by Django 4.1.1 on 2022-09-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_rename_quantity_productmaterialconsumption_cement_and_more'),
        ('materials', '0003_rawmaterialusage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='available_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialusage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productmaterialconsumption'),
        ),
    ]
