# Generated by Django 4.1.1 on 2022-10-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_branch_manager_alter_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmaterialsale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='branchmaterialsale',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.branchmaterialcounts'),
        ),
    ]
