# Generated by Django 4.1.1 on 2022-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curingstock',
            name='damaged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='curingstock',
            name='quantity_transfered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
