# Generated by Django 4.1.1 on 2022-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='D8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='D8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
