# Generated by Django 4.1.1 on 2022-09-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_alter_production_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='transfered_to_curing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CuringStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(auto_now_add=True)),
                ('curing_days', models.PositiveIntegerField(default=10)),
                ('transfered_to_ready', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.production')),
            ],
        ),
    ]
