# Generated by Django 4.1.1 on 2022-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_curingstock_damaged_curingstock_quantity_transfered'),
    ]

    operations = [
        migrations.AddField(
            model_name='moulding',
            name='damgess',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='moulding',
            name='qty_transfered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
