# Generated by Django 4.1.1 on 2022-10-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_moulding_qty_to_be_produced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestimestamp',
            name='sale_branch',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='RasiseProductionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.readyforsalestock')),
            ],
        ),
    ]
