# Generated by Django 4.1.1 on 2022-09-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_production_transfered_to_curing_curingstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.curingstock')),
            ],
        ),
    ]
