# Generated by Django 4.1.1 on 2022-09-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_moulding_damgess_moulding_qty_transfered'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.readyforsalestock')),
            ],
        ),
    ]
