# Generated by Django 4.1.1 on 2022-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_readystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='readystock',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
