# Generated by Django 4.1.1 on 2022-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_salestimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
