# Generated by Django 4.1.1 on 2022-09-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_readystock_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='readystock',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='actual_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='cement_bags_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='damages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='dust_buckets_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='fuel_used_in_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='half_ballast_buckets_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='number_of_labourers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='oil_used_in_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='quarter_ballast_buckets_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='river_sand_buckets_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='sand_buckets_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='target_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='wage_per_labourer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='white_cement_bags_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
