# Generated by Django 4.1.1 on 2022-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_readystock_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readystock',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
