# Generated by Django 4.1.1 on 2022-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_readystock_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='readystock',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
