# Generated by Django 4.1.1 on 2022-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_readystock_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readystock',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
