# Generated by Django 4.1.1 on 2022-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_readystock_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='readystock',
            name='selling',
            field=models.BooleanField(default=False),
        ),
    ]
