# Generated by Django 4.1.1 on 2022-09-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rawmaterialusage_date'),
        ('production', '0010_readystock_selling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('material', models.ManyToManyField(to='materials.rawmaterial')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
        ),
    ]
