# Generated by Django 4.1.1 on 2022-09-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rawmaterialusage_date'),
        ('production', '0011_productmaterialconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterialconsumption',
            name='material',
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='material',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.rawmaterial'),
        ),
    ]
