# Generated by Django 4.1.1 on 2022-09-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_remove_productmaterialconsumption_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moulding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_production', models.IntegerField(blank=True, null=True)),
                ('qty_produced', models.IntegerField(blank=True, null=True)),
                ('number_of_labourers', models.IntegerField(blank=True, null=True)),
                ('wage_per_labourer', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productmaterialconsumption')),
            ],
        ),
    ]
