# Generated by Django 4.1.1 on 2022-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_moulding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaterialconsumption',
            old_name='quantity',
            new_name='cement',
        ),
        migrations.RemoveField(
            model_name='productmaterialconsumption',
            name='material',
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='diesel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='dust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='half_ballast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='oil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='quarter_ballast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='river_sand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='sand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='white_cement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
