# Generated by Django 4.1.1 on 2022-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_rename_quantity_productmaterialconsumption_cement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moulding',
            name='target_production',
        ),
        migrations.AddField(
            model_name='moulding',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moulding',
            name='transfered_to_curing',
            field=models.BooleanField(default=False),
        ),
    ]
