# Generated by Django 4.1.1 on 2022-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_remove_moulding_target_production_moulding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='pumice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
