# Generated by Django 4.1.1 on 2022-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_productmaterialconsumption_pumice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='cement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='dust',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='half_ballast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='oil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='pumice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='quarter_ballast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='river_sand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='sand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productmaterialconsumption',
            name='white_cement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
