# Generated by Django 4.1.1 on 2022-09-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_productmaterialconsumption_cement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moulding',
            old_name='qty_produced',
            new_name='qty_to_be_produced',
        ),
    ]
