# Generated by Django 4.1.1 on 2022-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_rename_qty_produced_moulding_qty_to_be_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='moulding',
            name='production_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
