# Generated by Django 4.1.1 on 2022-09-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_alter_curingstock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curingstock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.production'),
        ),
    ]
