# Generated by Django 4.1.1 on 2022-09-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_alter_curingstock_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyForSaleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=False)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.curingstock')),
            ],
        ),
    ]
