# Generated by Django 4.1.1 on 2022-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_readyforsalestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curingstock',
            name='curing_days',
        ),
        migrations.AddField(
            model_name='productmaterialconsumption',
            name='curing_days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
