# Generated by Django 4.1.1 on 2022-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_remove_curingstock_curing_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curingstock',
            name='damages_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moulding',
            name='damages_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readyforsalestock',
            name='damages_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
