# Generated by Django 4.1.1 on 2022-09-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ready', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Curing', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('damages', models.IntegerField(null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
        ),
        migrations.CreateModel(
            name='SemiReleaseQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('diesel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('white_cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('river_sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quarter_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('half_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pumice', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dust', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.moulding')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('diesel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('white_cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('river_sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quarter_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('half_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pumice', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dust', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productmaterialconsumption')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_damaged', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('image', models.FileField(default='', upload_to='damages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.moulding')),
            ],
        ),
    ]
