# Generated by Django 4.1.1 on 2022-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='Curing',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stage',
        ),
        migrations.AddField(
            model_name='stock',
            name='Ready',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
