# Generated by Django 4.1.1 on 2022-09-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseqty',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.moulding'),
        ),
    ]
