# Generated by Django 4.1.1 on 2022-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='reason_for_damage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
