# Generated by Django 4.1.1 on 2022-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseqty',
            name='D8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='semireleaseqty',
            name='D8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
