# Generated by Django 4.1.1 on 2022-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_releaseqty_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='image',
            field=models.FileField(null=True, upload_to='damages'),
        ),
    ]
