# Generated by Django 4.1.1 on 2022-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_quantity_stock_curing_remove_stock_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='damages',
            field=models.IntegerField(null=True),
        ),
    ]
