# Generated by Django 4.1.1 on 2022-10-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_moulding_qty_to_be_produced_and_more'),
        ('stocks', '0002_damage_reason_for_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.moulding')),
            ],
        ),
    ]
