# Generated by Django 4.1.1 on 2022-09-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_alter_production_date_and_more'),
        ('stocks', '0003_stock_damages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('production', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('arranging', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
        ),
    ]
