# Generated by Django 4.1.1 on 2022-10-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_moulding_qty_to_be_produced_and_more'),
        ('stocks', '0003_stockcounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcounts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productmaterialconsumption'),
        ),
    ]
