# Generated by Django 4.1.1 on 2022-09-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_alter_curingstock_product'),
        ('stocks', '0004_remove_stock_name_stock_product_alter_stock_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseQty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('diesel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('white_cement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('river_sand', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quarter_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('half_ballast', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pumice', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dust', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productmaterialconsumption')),
            ],
        ),
    ]
