# Generated by Django 4.1.1 on 2022-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_damage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='damages')),
                ('quantity_damaged', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
