# Generated by Django 4.1.1 on 2022-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stockcounts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcounts',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
