# Generated by Django 4.1.1 on 2022-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_releaseqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseqty',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
