# Generated by Django 4.1.1 on 2022-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_tdamage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('quantity_damaged', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_field_one', models.CharField(max_length=300, null=True)),
                ('extra_field_two', models.CharField(max_length=300, null=True)),
                ('extra_field_three', models.CharField(max_length=300, null=True)),
                ('extra_field_four', models.CharField(max_length=300, null=True)),
                ('extra_field_five', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
