# Generated by Django 4.1.1 on 2022-10-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_salestimestamp_sale_branch_and_more'),
        ('materials', '0002_branch_site_rawmaterial_confirm_received_and_more'),
        ('stocks', '0005_stockcounts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStockCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=200, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.site')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStockToSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.site')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStockToBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchStockSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
            ],
        ),
        migrations.CreateModel(
            name='BranchStockCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=200, null=True)),
                ('date', models.DateField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
            ],
        ),
    ]
