# Generated by Django 4.1.1 on 2022-10-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_branchmaterialcounts_branch_and_more'),
        ('production', '0003_salestimestamp_sale_branch_and_more'),
        ('stocks', '0006_sitestockcounts_dispatchstocktosite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstocksale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.branch'),
        ),
        migrations.AlterField(
            model_name='branchstockcounts',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.branch'),
        ),
        migrations.AlterField(
            model_name='sitestockcounts',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.site'),
        ),
        migrations.CreateModel(
            name='SiteStockUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.site')),
            ],
        ),
    ]
