# Generated by Django 4.1.1 on 2022-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_rename_arranging_damage_quantity_damaged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('PACKING', 'PACKING'), ('CURING', 'CURING'), ('TRANSPORTING', 'TRANSPORTING'), ('OFFLOADING', 'OFFLOADING')], max_length=20, null=True),
        ),
    ]
