# Generated by Django 4.1.1 on 2022-09-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stockrecording_extra_field_five_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecording',
            old_name='quantity_damaged',
            new_name='quantity',
        ),
    ]
