# Generated by Django 4.1.1 on 2022-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_damage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
