# Generated by Django 4.1.1 on 2022-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_damage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='image',
            field=models.FileField(default='', upload_to='damages'),
        ),
    ]
