# Generated by Django 4.1.1 on 2022-09-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_product_alter_production_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('client', models.CharField(max_length=300, null=True)),
                ('order_number', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
        ),
    ]
