# Generated by Django 4.1.1 on 2022-11-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('order_type', models.CharField(choices=[('LPO', 'LPO'), ('INVOICE', 'INVOICE'), ('CASH', 'CASH'), ('INTERNAL TRANSFER', 'INTERNAL TRANSFER')], max_length=30, null=True)),
                ('order_documents', models.FileField(blank=True, null=True, upload_to='orders')),
                ('date', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock')),
            ],
        ),
    ]
