# Generated by Django 4.1.1 on 2022-09-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_curingstock_damages_confirmed_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order_number',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_documents',
            field=models.FileField(default=True, upload_to='orders'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('PACKING', 'PACKING'), ('CURING', 'CURING'), ('TRANSPORTING', 'TRANSPORTING'), ('OFFLOADING', 'OFFLOADING')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.readyforsalestock'),
        ),
    ]
