# Generated by Django 4.1.1 on 2022-09-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_documents',
            field=models.FileField(blank=True, null=True, upload_to='orders'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('LPO', 'LPO'), ('INVOICE', 'INVOICE'), ('CASH', 'CASH'), ('INTERNAL TRANSFER', 'INTERNAL TRANSFER')], max_length=30, null=True),
        ),
    ]
